package com.myspace.merchantonboarding;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Merchant implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("unique entity number")
	private java.lang.String uen;
	@org.kie.api.definition.type.Label("ceo IC number")
	private java.lang.String ceoIC;
	@org.kie.api.definition.type.Label("net income of the merchant")
	private java.math.BigDecimal netIncome;
	@org.kie.api.definition.type.Label("total deposit in the bank of the merchant")
	private java.math.BigDecimal totalDeposit;
	@org.kie.api.definition.type.Label("value added tax ID")
	private java.lang.String vatID;
	@org.kie.api.definition.type.Label("number of merchant's employees")
	private int numberOfEmployees;
	@org.kie.api.definition.type.Label("registered location or city")
	private java.lang.String registeredLocation;

	@org.kie.api.definition.type.Label("Assessment Result")
	private java.lang.String result;

	@org.kie.api.definition.type.Label("Financial Assessment Certainty Factor")
	private java.lang.Double CFfinancial;

	@org.kie.api.definition.type.Label("Operational Assessment Certainty Factor")
	private java.lang.Double CFoperational;

	@org.kie.api.definition.type.Label("Credibility Assessment Certainty Factor")
	private java.lang.Double CFcredibility;

	@org.kie.api.definition.type.Label(value = "merchant company establish year")
	private java.lang.Integer yearOfEstablishment;

	public Merchant() {
	}

	public java.lang.String getUen() {
		return this.uen;
	}

	public void setUen(java.lang.String uen) {
		this.uen = uen;
	}

	public java.lang.String getCeoIC() {
		return this.ceoIC;
	}

	public void setCeoIC(java.lang.String ceoIC) {
		this.ceoIC = ceoIC;
	}

	public java.math.BigDecimal getNetIncome() {
		return this.netIncome;
	}

	public void setNetIncome(java.math.BigDecimal netIncome) {
		this.netIncome = netIncome;
	}

	public java.math.BigDecimal getTotalDeposit() {
		return this.totalDeposit;
	}

	public void setTotalDeposit(java.math.BigDecimal totalDeposit) {
		this.totalDeposit = totalDeposit;
	}

	public java.lang.String getVatID() {
		return this.vatID;
	}

	public void setVatID(java.lang.String vatID) {
		this.vatID = vatID;
	}

	public int getNumberOfEmployees() {
		return this.numberOfEmployees;
	}

	public void setNumberOfEmployees(int numberOfEmployees) {
		this.numberOfEmployees = numberOfEmployees;
	}

	public java.lang.String getRegisteredLocation() {
		return this.registeredLocation;
	}

	public void setRegisteredLocation(java.lang.String registeredLocation) {
		this.registeredLocation = registeredLocation;
	}

	public java.lang.String getResult() {
		return this.result;
	}

	public void setResult(java.lang.String result) {
		this.result = result;
	}

	public java.lang.Double getCFfinancial() {
		return this.CFfinancial;
	}

	public void setCFfinancial(java.lang.Double CFfinancial) {
		this.CFfinancial = CFfinancial;
	}

	public java.lang.Double getCFoperational() {
		return this.CFoperational;
	}

	public void setCFoperational(java.lang.Double CFoperational) {
		this.CFoperational = CFoperational;
	}

	public java.lang.Double getCFcredibility() {
		return this.CFcredibility;
	}

	public void setCFcredibility(java.lang.Double CFcredibility) {
		this.CFcredibility = CFcredibility;
	}

	public java.lang.Integer getYearOfEstablishment() {
		return this.yearOfEstablishment;
	}

	public void setYearOfEstablishment(java.lang.Integer yearOfEstablishment) {
		this.yearOfEstablishment = yearOfEstablishment;
	}

	public Merchant(java.lang.String uen, java.lang.String ceoIC,
			java.math.BigDecimal netIncome, java.math.BigDecimal totalDeposit,
			java.lang.String vatID, int numberOfEmployees,
			java.lang.String registeredLocation, java.lang.String result,
			java.lang.Double CFfinancial, java.lang.Double CFoperational,
			java.lang.Double CFcredibility,
			java.lang.Integer yearOfEstablishment) {
		this.uen = uen;
		this.ceoIC = ceoIC;
		this.netIncome = netIncome;
		this.totalDeposit = totalDeposit;
		this.vatID = vatID;
		this.numberOfEmployees = numberOfEmployees;
		this.registeredLocation = registeredLocation;
		this.result = result;
		this.CFfinancial = CFfinancial;
		this.CFoperational = CFoperational;
		this.CFcredibility = CFcredibility;
		this.yearOfEstablishment = yearOfEstablishment;
	}

}