package com.myspace.merchantonboarding;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Merchant implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "unique entity number")
	private java.lang.String uen;
	@org.kie.api.definition.type.Label(value = "ceo IC number")
	private java.lang.String ceoIC;
	@org.kie.api.definition.type.Label(value = "net income of the merchant")
	private java.math.BigDecimal netIncome;
	@org.kie.api.definition.type.Label(value = "total deposit in the bank of the merchant")
	private java.math.BigDecimal totalDeposit;
	@org.kie.api.definition.type.Label(value = "value added tax ID")
	private java.lang.String vatID;
	@org.kie.api.definition.type.Label(value = "number of merchant's employees")
	private int numberOfEmployees;
	@org.kie.api.definition.type.Label(value = "merchant company establish date")
	private java.util.Date dateOfEstablishment;
	@org.kie.api.definition.type.Label(value = "registered location or city")
	private java.lang.String registeredLocation;

	public Merchant() {
	}

	public java.lang.String getUen() {
		return this.uen;
	}

	public void setUen(java.lang.String uen) {
		this.uen = uen;
	}

	public java.lang.String getCeoIC() {
		return this.ceoIC;
	}

	public void setCeoIC(java.lang.String ceoIC) {
		this.ceoIC = ceoIC;
	}

	public java.math.BigDecimal getNetIncome() {
		return this.netIncome;
	}

	public void setNetIncome(java.math.BigDecimal netIncome) {
		this.netIncome = netIncome;
	}

	public java.math.BigDecimal getTotalDeposit() {
		return this.totalDeposit;
	}

	public void setTotalDeposit(java.math.BigDecimal totalDeposit) {
		this.totalDeposit = totalDeposit;
	}

	public java.lang.String getVatID() {
		return this.vatID;
	}

	public void setVatID(java.lang.String vatID) {
		this.vatID = vatID;
	}

	public int getNumberOfEmployees() {
		return this.numberOfEmployees;
	}

	public void setNumberOfEmployees(int numberOfEmployees) {
		this.numberOfEmployees = numberOfEmployees;
	}

	public java.util.Date getDateOfEstablishment() {
		return this.dateOfEstablishment;
	}

	public void setDateOfEstablishment(java.util.Date dateOfEstablishment) {
		this.dateOfEstablishment = dateOfEstablishment;
	}

	public java.lang.String getRegisteredLocation() {
		return this.registeredLocation;
	}

	public void setRegisteredLocation(java.lang.String registeredLocation) {
		this.registeredLocation = registeredLocation;
	}

	public Merchant(java.lang.String uen, java.lang.String ceoIC,
			java.math.BigDecimal netIncome, java.math.BigDecimal totalDeposit,
			java.lang.String vatID, int numberOfEmployees,
			java.util.Date dateOfEstablishment,
			java.lang.String registeredLocation) {
		this.uen = uen;
		this.ceoIC = ceoIC;
		this.netIncome = netIncome;
		this.totalDeposit = totalDeposit;
		this.vatID = vatID;
		this.numberOfEmployees = numberOfEmployees;
		this.dateOfEstablishment = dateOfEstablishment;
		this.registeredLocation = registeredLocation;
	}

}